### ISSUE TITLE
Permissions INSTALL_PACKAGES, DELETE_PACKAGES and REQUEST_INSTALL_PACKAGES with ADB?

### ISSUE THREAD

**Issue by JeremyStarTM** [marchingon12/AuroraStore#1]
Hello, i have a Samsung Galaxy A51, it runs Android 11.
I try to enable the permissions above (INSTALL_PACKAGES, DELETE_PACKAGES and REQUEST_INSTALL_PACKAGES) with adb.
My command for INSTALL_PACKAGES:
_adb shell pm grant com.aurora.store android.permission.REQUEST_INSTALL_PACKAGES_

And i get the following error:
_Exception occurred while executing 'grant':
java.lang.SecurityException: Permission android.permission.REQUEST_INSTALL_PACKAGES requested by com.aur
ora.store is not a changeable permission type
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(Ba
sePermission.java:458)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(Perm
issionManagerService.java:1538)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(Perm
issionManagerService.java:1492)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionMa
nagerService.java:1484)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShell
Command.java:2325)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:25
9)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26546)
        at android.os.Binder.shellCommand(Binder.java:965)
        at android.os.Binder.onTransact(Binder.java:839)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5206)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5247)
        at android.os.Binder.execTransactInternal(Binder.java:1195)
        at android.os.Binder.execTransact(Binder.java:1159)_

Can someone help me with this. Maybe i can enable the root permissions with that.

Thanks in advance,
- JeremyStar™

**Comment by marchingon12** [comment]
Please head over to the GitLab repo and open an issue there. This repo is mainly for mirroring the repository code on GitLab.

**Comment by JeremyStarTM** [comment]
Okay thank you
